/* This file is automatically generated. DO NOT EDIT! */

#ifndef _icai1_h
#define _icai1_h


void icai1_init (int na    /* filter length */, 
		 float* aa /* filter [na] */, 
		 int lag   /* filter lag (lag=1 is causal) */);
/*< initialize >*/


void icai1_lop (bool adj, bool add, int nx, int ny, float* xx, float* yy);
/*< linear operator >*/

#endif
