/* This file is automatically generated. DO NOT EDIT! */

#ifndef _tcai1_ns_h
#define _tcai1_ns_h


#include <rsf.h>


void tcai1_ns_init (int na          /* filter size */, 
		 const float* aa /* filter [na] */);
/*< initialize >*/


void tcai1_ns_lop (bool adj, bool add, int nx, int ny, float* xx, float* yy);
/*< linear operator >*/

#endif
